from CursorControl.rl.oracles.keyboard_oracle import KeyboardOracle
from CursorControl.rl.oracles.light_switch_oracle import LightSwitchOracle
from CursorControl.rl.oracles.straight_line_oracle import StraightLineOracle
from CursorControl.rl.oracles.tracing_oracle import TracingOracle
